name: r_angular_blob
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  angular: ^6.0.0-alpha+1
  angular_components: ^0.14.0-alpha+1
  angular_router: ^2.0.0-alpha+24
  http: ^0.12.0+4
  http_multi_server: ^2.2.0
  angular_forms: ^2.1.4
  markdown: ^2.1.3
  angular_analyzer_plugin: ^1.0.0-alpha+1 
dev_dependencies:
  angular_test: ^2.3.0
  build_runner: ^1.6.0
  build_test: ^0.10.8
  build_web_compilers: ^2.3.0
  pedantic: ^1.8.0
  test: ^1.6.0
  sass_builder: ^2.1.3
